version: '3.8'

services:
  apollo-collaboration-server:
    image: public.ecr.aws/p1r0y7k4/apollo-collaboration-server-alpha:latest
    volumes:
      - uploaded-files-volume:/data/uploads
    ports:
      - 3999:3999
    env_file: ./apollo.env
    depends_on:
      mongodb-init:
        condition: service_completed_successfully

  jbrowse-plugin-apollo:
    image: public.ecr.aws/p1r0y7k4/jbrowse-plugin-apollo-alpha:latest
    ports:
      - 9000:80

  jbrowse-web:
    image: public.ecr.aws/p1r0y7k4/jbrowse-web-apollo-alpha:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/config:/usr/local/apache2/htdocs/data

  mongodb:
    image: mongo
    volumes:
      - mongodb-volume:/data/db
    command: --replSet rs0

  # this container will exit after initializing the replica set
  mongodb-init:
    image: mongo
    depends_on:
      - mongodb
    command:
      mongosh mongodb://mongodb:27017 --eval 'try {rs.initiate();} catch {}'

volumes:
  mongodb-volume: null
  uploaded-files-volume: null
